[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
unicode-bom = "2.0.3"
walkdir = "2.5.0"
yaml-rust2 = "0.10.1"
fluent-syntax = "0.11.1"
hex = "0.4.3"
sha2 = "0.10.8"
pathdiff = "0.2.3"
