[net]
max_connections = 1024
pvs_range = 20.0
pvs_priority_range = 30.0
tickrate = 60

[game]
maxplayers = 150
soft_max_players = 100
hostname = "🌒 Project Eclipse - Expedition! 🌒"
#desc = "🌒Начни свое путешествие на секторе ЭКЛИПС прямо сейчас!\n🌒Система TTS 200+ голосов, выбери себе голос по вкусу!\n🌒Уникальная система сохранения своего шаттла, построй свой шаттл мечты!\n\n💎На сервере средний уровень отыгрыша РП.\n💎Смены идут по 72 часа, достаточно для воплощения ваших фантазий!\n💎Множество своих уникальных систем, улучшений и разработок!\n💎Постройте шаттл своей мечты, ограничение только ваша фантазия!\n💎Отзывчивая и дружелюбная администрация!\n💎Наш сервер работает на сверхмощном железе со стабильным тикрейтом в 60!\n💎Полная локализация и постоянные обновления!\n"
cryo_sleep_rejoining = true
defaultpreset = "Expedition"
map_pool = "ExpeditionShipMapPool"

[vote]
preset_enabled = false
map_enabled = false
restart_enabled = false

[shuttle]
auto_call_time = 4320
arrivals = false
emergency_dock_time = 360 # an extra 2 minutes over the default
emergency_transit_time_min = 300
auto_call_extension_time = 45
emergency_early_launch_allowed = false

[rules]
time = 60

[atmos]
space_wind = true

[viewport]
minimum_width = 15
maximum_width = 26

[ic]
flavor_text = true
punctuation = true

[worldgen]
enabled = true

[replay]
client_recording_enabled = false

[server]
id = "eclipse_expedition"
rules_file = "StandardRuleset"

[infolinks]
bug_report = "https://github.com/Project-Eclipse-SS14/Eclipse-Expedition/issues/new/choose"
discord = "https://discord.gg/5J9Q8WuJFd"
#forum = ""
github = "https://github.com/Project-Eclipse-SS14/Eclipse-Expedition"
patreon = ""
website = "https://boosty.to/project_eclipse"
#wiki = ""
#appeal = ""

[biomass]
easy_mode = false # reclaimer can work on soul-ful bodies, mrp server

[control]
storage_limit = 6

[discord]
rich_main_icon_id = "https://shorturl.at/nHmHm"

[chat]
max_message_length = 3000