[package]
name = "changelog"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
octocrab = "0.44.1"
regex = "1.11.1"
tokio = { version = "1.46.1", features = ["full"] }
unicode-bom = "2.0.3"
yaml-rust2 = "0.10.3"
