[package]
name = "prototypes_extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
fluent-syntax = "0.11.1"
hex = "0.4.3"
log = "0.4.27"
pathdiff = "0.2.3"
sha2 = "0.10.8"
simple_logger = "5.0.0"
yaml-rust2 = "0.10.1"
