name: Generate changelogs

on:
  pull_request_target:
    types:
      - closed

concurrency:
  group: changelogs

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_PATH: Resources/Changelog/Eclipse.yml
  PR_NUMBER: ${{ github.event.number }}

jobs:
  generate_changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: master

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Generate Changelog
        run: |
          cargo run --manifest-path Tools/_Eclipse/changelog/Cargo.toml
        shell: bash

      - name: Commit Changelog
        run: |
          git pull origin master
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        continue-on-error: true
