name: Publish Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
 publish_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:

    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        ref: master

    - name: Publish changelog
      run: Tools/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK }}
